id: active-directory
displayName: Active Directory monitoring
description: |
  Quickly monitor your Active Directory environment for a comprehensive view of health and availability.
install:
  primary:
    link:
      url: https://newrelic.com
icon: logo.svg
