name: Add Commit Status
description: Adds status to a commit
inputs:
  context:
    description: The context passed to `createCommitStatus`
    required: true
  github_token:
    description: Github token passed to github-script
    required: true
  state:
    description: The state to assign to the commit
    required: true
runs:
  using: composite
  steps:
    - name: Add commit status
      uses: actions/github-script@v6
      with:
        github-token: inputs.github_token
        script: |
          const {head_sha, status, repository, html_url} = context.payload.workflow_run;
          const {owner, name} = repository;

          const args = {
            owner: owner.login,
            repo: name,
            sha: head_sha,
            state: process.env.INPUT_STATE,
            target_url: html_url,
            context: process.env.INPUT_CONTEXT
          }

          console.log('Calling `createCommitStatus` with args:', args);

          const result = await github.rest.repos.createCommitStatus(args)

          console.log("Result:", result)