id: circleci
displayName: CircleCI
description: |
  Provides views to track the performance and health of your continuous integration and deployment pipelines.
icon: logo.png
install:
  primary:
    nerdlet:
      requires_account: false
      nerdletId: marketplace.install-data-source
      nerdletState:
        dataSourceId: circleci
        frameworkConfigId: circleci
  fallback:
    link:
      url: https://circleci.com/docs/2.0/webhooks/
keywords:
  - newrelic partner
  - devops
  - circleci
  - circle
  - cicd
  - featured
  - logs
categoryTerms:
  - newrelic partner
  - logs
