id: apache-druid
displayName: Apache Druid
description: |
   Enhance your monitoring and analysis of Apache Druid with New Relic. Gain comprehensive insights and optimize performance seamlessly with our advanced tools and features.
install:
  primary:
    nerdlet:
      nerdletId: marketplace.install-data-source
      nerdletState:
        dataSourceId: apache-druid
        frameworkConfigId: apache-druid
      requiresAccount: false
keywords:
  - apache-druid
  - apache
  - druid
